sillsdev/EthnoLib

README.md
components/language-picker/README.md
components/language-picker/common/find-language/index.ts
components/language-picker/common/find-language/languageTagUtils.spec.ts
components/language-picker/common/find-language/languageTagUtils.ts
components/language-picker/common/find-language/package.json
components/language-picker/common/find-language/regionsAndScripts.ts
components/language-picker/common/find-language/searchResultModifiers.ts
components/language-picker/common/find-language/tsconfig.json
components/language-picker/react/language-chooser-react-mui/package.json
components/language-picker/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx
components/language-picker/react/language-chooser-react-mui/src/OptionCard.tsx
components/language-picker/react/language-chooser-react-mui/src/main.tsx
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/3)

Language chooser unreviewed

---

components/language-chooser/common/find-language/vitest.config.ts
components/language-chooser/react/language-chooser-react-mui/package.json
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/10)

upgrade vitest and straighten up dependencies

---

components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/.storybook/manager.ts
components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageButton.tsx
components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx
components/language-chooser/react/language-chooser-react-mui/src/Demo.stories.tsx
components/language-chooser/react/language-chooser-react-mui/src/Demo.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/OptionCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/ScriptCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/colors.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/11)

fix: fixes, css changes, revamped demo

---

components/language-chooser/react/language-chooser-react-mui/src/Demo.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/13)

make width shrinkable

---

.github/workflows/release.yml
nx.json

Example changelog: 
```
- test ([3038282](https://github.com/sillsdev/EthnoLib/commit/3038282))
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/14)

commit version number and changelog

---

components/language-chooser/react/language-chooser-react-mui/src/LanguageCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/17)

fix: better layout for very narrow widths

---

components/language-chooser/common/find-language/langtagProcessing.ts
components/language-chooser/common/find-language/package.json
components/language-chooser/common/find-language/tsconfig.json
components/language-chooser/common/find-language/tsconfig.lib.json
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/18)

fix: langtagProcessing.ts script

---

components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageButton.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/colors.ts

https://issues.bloomlibrary.org/youtrack/issue/BL-13988/Revision-to-customize-unlisted-button
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/21)

BL-13988 revisions to unlisted button

---

components/language-chooser/common/find-language/matchingSubstringDemarcation.spec.ts
components/language-chooser/common/find-language/matchingSubstringDemarcation.ts
components/language-chooser/react/language-chooser-react-mui/src/Demo.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/index.ts
package-lock.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/20)

re-exports and strip demarcation from output

---

.gitignore
components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts
components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx
components/language-chooser/react/language-chooser-react-mui/src/FormFieldLabel.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/TextInput.tsx
components/language-chooser/react/language-chooser-react-mui/src/colors.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/22)

BL-13987 subdialogs

---

components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/DialogDemo.stories.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/DialogDemo.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/DummyRightPanelComponent.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/PageDemo.stories.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/PageDemo.tsx
components/language-chooser/react/language-chooser-react-mui/src/main.tsx

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/23)

add prop for an additional component on the right side, storybook

---

components/language-chooser/react/language-chooser-react-mui/src/FormFieldLabel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/25)

fix: allow labels to wrap

---

components/language-chooser/common/find-language/index.ts
components/language-chooser/common/find-language/scriptSamples.ts
components/language-chooser/react/language-chooser-react-mui/src/ScriptCard.tsx

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/28)

add script samples for 9 most common scripts

---

components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/DialogDemo.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/29)

fix: reopen with custom display name

---

components/language-chooser/react/common/language-chooser-react-hook/index.ts
components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.spec.ts
components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.ts
components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/DialogDemo.stories.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/DialogDemo.tsx
components/language-chooser/react/language-chooser-react-mui/src/main.tsx

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/31)

fix: preload search string, more demos

---

.github/workflows/release.yml
components/language-chooser/common/find-language/searchForLanguage.ts
components/language-chooser/common/find-language/searchResultModifiers.spec.ts
components/language-chooser/common/find-language/searchResultModifiers.ts
components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts
components/language-chooser/react/language-chooser-react-mui/src/demos/DialogDemo.tsx
components/language-chooser/react/language-chooser-react-mui/tsconfig.storybook.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/33)

Chinese case and other tweaks

---

components/language-chooser/common/find-language/searchForLanguage.spec.ts
components/language-chooser/common/find-language/searchForLanguage.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/34)

fix: prioritize whole word matches then prefix matches

---

.vscode/settings.json
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
eslint.config.mjs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/37)

chore: Wire up eslint for react hooks

---

components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts
components/language-chooser/react/language-chooser-react-mui/README.md
components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/DialogDemo.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/LanguageChooserDialog.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/PageDemo.tsx
components/language-chooser/react/language-chooser-react-mui/src/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/36)

fix: dialog buttons and header should not be baked into the component

---

components/language-chooser/common/find-language/searchForLanguage.ts
components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.spec.ts
components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.ts
components/language-chooser/react/language-chooser-react-mui/src/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/38)

fix: langtag bug fix and region lookup

---

components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/DialogDemo.stories.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/DummyRightPanelComponent.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/PageDemo.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/ThemeDemo.stories.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/ThemeDemo.tsx

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/44)

storybook improvements

---

components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/43)

Auto-scrolling

---

components/language-chooser/react/language-chooser-react-mui/README.md
components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageButton.tsx
components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx
components/language-chooser/react/language-chooser-react-mui/src/FormFieldLabel.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/OptionCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/ScriptCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/colors.ts
components/language-chooser/react/language-chooser-react-mui/src/demos/DialogDemo.stories.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/DialogDemo.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/DummyRightPanelComponent.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/LanguageChooserDialog.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/PageDemo.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/ThemeDemo.stories.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/ThemeDemo.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/39)

MUI theming colors

---

components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/45)

focus search bar at start and on X

---

components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx
components/language-chooser/react/language-chooser-react-mui/src/FormFieldLabel.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/ScriptCard.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/46)

fix: move "required" label, various spacing tweaks

---

.eslintignore
.eslintrc.json
.github/workflows/release.yml
.vscode/extensions.json
components/language-chooser/react/language-chooser-react-mui/.eslintrc.json
components/language-chooser/react/language-chooser-react-mui/.gitignore
components/language-chooser/react/language-chooser-react-mui/README.md
components/language-chooser/react/language-chooser-react-mui/e2e/cardSelection.e2e.ts
components/language-chooser/react/language-chooser-react-mui/e2e/customizationDialog.e2e.ts
components/language-chooser/react/language-chooser-react-mui/e2e/e2eHelpers.ts
components/language-chooser/react/language-chooser-react-mui/e2e/languageSearch.e2e.ts
components/language-chooser/react/language-chooser-react-mui/e2e/selectionCompleteness.e2e.ts
components/language-chooser/react/language-chooser-react-mui/package.json
components/language-chooser/react/language-chooser-react-mui/playwright.config.ts
components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageButton.tsx
components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/OptionCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/ScriptCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/demos/LanguageChooserDialog.tsx
components/language-chooser/react/language-chooser-react-mui/vite.config.ts
nx.json
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/48)

playwright e2e testing

---

.github/workflows/release.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/50)

fix: try to fix ci e2e test running

---

components/language-chooser/react/language-chooser-react-mui/vite.config.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/51)

add mui etc to vite config external

---

components/language-chooser/react/language-chooser-react-mui/package.json
components/language-chooser/react/language-chooser-react-mui/vite.config.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/52)

make mui and emotion/react external in rollupOptions

---

.github/workflows/release.yml
.github/workflows/runTests.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/53)

GHA to run tests on PR

---

components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/57)

fix: try to trigger release

---

components/language-chooser/react/language-chooser-react-mui/README.md
components/language-chooser/react/language-chooser-react-mui/src/LanguageCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/OptionCard.tsx
components/language-chooser/react/language-chooser-react-mui/src/ScriptCard.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/58)

BL-14222 refactor coloring for Bloom mui theming

---

components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/67)

fix: BL-14355 don't preselect default script

---

components/language-chooser/react/language-chooser-react-mui/e2e/customizationDialog.e2e.ts
components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/66)

fix: BL-14315 unwanted scrollbar in customization dialog

---

components/language-chooser/common/find-language/searchForLanguage.spec.ts
components/language-chooser/common/find-language/searchForLanguage.ts
components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.spec.ts
components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.ts
components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts
components/language-chooser/react/language-chooser-react-mui/src/demos/LanguageChooserDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/70)

fix: BL-14355 fix preloaded langs inconsistency

---

components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/PrimaryTooltip.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/69)

fix: BL-14361 tooltip prompts

---

components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.ts
components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts
components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx
components/language-chooser/react/language-chooser-react-mui/src/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/73)

Bl 14355 customization fixes

---

components/language-chooser/common/find-language/scriptSamples.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/74)

fix: BL-14325 add script samples for major indian scripts

---

components/language-chooser/react/common/I18nProvider.tsx
components/language-chooser/react/language-chooser-react-mui/.storybook/preview.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/85)

fix: Default to browser language (BL-14005)

---

.github/workflows/release.yml
.github/workflows/runTests.yml
components/language-chooser/common/find-language/package.json
components/language-chooser/react/common/language-chooser-react-hook/package.json
components/language-chooser/react/language-chooser-react-mui/package.json
package-lock.json
package.json

Also updated a couple dependencies
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/89)

Upgrade to node v22

---

components/language-chooser/react/language-chooser-react-mui/src/demos/LanguageChooserDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/90)

Escape or click outside dialog should be the same as cancel (BL-14378)

---

components/language-chooser/common/find-language/README.md
components/language-chooser/common/find-language/searchForLanguage.spec.ts
components/language-chooser/common/find-language/searchForLanguage.ts
components/language-chooser/common/find-language/searchResultModifiers.spec.ts
components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/86)

BL-14405 search order and speed improvements

---

components/language-chooser/common/find-language/README.md
components/language-chooser/common/find-language/languageTagUtils.spec.ts
components/language-chooser/common/find-language/languageTagUtils.ts
components/language-chooser/common/find-language/matchingSubstringDemarcation.spec.ts
components/language-chooser/common/find-language/matchingSubstringDemarcation.ts
components/language-chooser/common/find-language/searchForLanguage.spec.ts
components/language-chooser/common/find-language/searchForLanguage.ts
components/language-chooser/common/find-language/searchResultModifiers.ts
components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts
components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx
components/language-chooser/react/language-chooser-react-mui/src/PartiallyBoldedTypography.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/93)

Bl 14423 fix match highlighting

---

components/language-chooser/common/find-language/languageTagUtils.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/95)

Limit final (private) subtag to 8 characters (BL-14806)

---

components/language-chooser/common/find-language/languageTagUtils.spec.ts
components/language-chooser/common/find-language/languageTagUtils.ts
components/language-chooser/common/find-language/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/98)

Handle private variants when trying to shorten tags (BL-14854)

---

components/language-chooser/common/find-language/languageTagUtils.spec.ts
components/language-chooser/common/find-language/languageTagUtils.ts
components/language-chooser/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx

alert about variant rules (e.g. must be longer than 4 or 5 characters)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/103)

BL-14904 Check variant format

---

components/language-chooser/common/find-language/languageTagUtils.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/106)

fix: fix error reopening with no language tag

---

README.md
components/language-chooser/common/find-language/package.json
components/language-chooser/react/common/language-chooser-react-hook/package.json
components/language-chooser/react/language-chooser-react-mui/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/108)

BL-14971 make packages inherit the node version for volta

---

components/language-chooser/common/find-language/languageTagUtils.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/EthnoLib/115)

fix: BL-15161 clear display name for custom langtags
